### PR TITLE
Fixes #104

### LINKED ISSUE #104: method names of of Sync.Run and Sync.RunAsync the other way around
Method names of of `Sync.Run` and `Sync.RunAsync` are for some reason messed up. They should be named the other way around.

### PR DESCRIPTION
**Pull request by fvandillen**
Changed the names of the functions and the documentation above it.
Are the references to the function in LogWriter and PrintTraceListener correct this way?

### CODE REVIEW

**Comment by rrev** [comment]
Travis-ci build is bugged. :/

You should change return type of `RunAsync` to `async Task` and change `Run` to return `void`. Not just the name

**Comment by fvandillen** [comment]
@rrev thanks, put in an additional commit. Should be fixed.

**Comment by ikkentim** [comment]
I've thought about this for a bit, and I think the method `RunSync` should be the awaitable method because it is called _asynchronously_. and the `Run` method should merely call the action on the main thread.

This means the methods should look like this:

``` C#
void Run(Action);
async Task RunAsync(Action);
```

This is actually what the functions currently look like, which means that issue #104 is actually an invalid issue. If you look closely at this pull request (files changed) you can see that all you do in the `Sync` class is changing the order of the methods in the class.

This is what happens when I add issues when I'm tired :-1... I appreciate the time you took to fix this issue, but as it turns out, it doesn't need fixing.

**Comment by fvandillen** [comment]
No problem! Enjoy your weekend!

**Pull request closed without merging**
